// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutMeAdmin: typeof import('./src/components/admin/AboutMeAdmin.vue')['default']
    AnnoAdmin: typeof import('./src/components/admin/AnnoAdmin.vue')['default']
    ArticleAdmin: typeof import('./src/components/admin/ArticleAdmin.vue')['default']
    DeletedArticle: typeof import('./src/components/admin/DeletedArticle.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ErrorLogAdmin: typeof import('./src/components/admin/ErrorLogAdmin.vue')['default']
    FilingAdmin: typeof import('./src/components/admin/FilingAdmin.vue')['default']
    FriendsAdmin: typeof import('./src/components/admin/FriendsAdmin.vue')['default']
    Header: typeof import('./src/components/nav/Header.vue')['default']
    Index: typeof import('./src/components/Index.vue')['default']
    MessageAdmin: typeof import('./src/components/admin/MessageAdmin.vue')['default']
    Publish: typeof import('./src/components/edit/Publish.vue')['default']
    PublishFrom: typeof import('./src/components/PublishFrom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagAdmin: typeof import('./src/components/admin/TagAdmin.vue')['default']
    THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TruckLogAdmin: typeof import('./src/components/admin/TruckLogAdmin.vue')['default']
    TSubmenu: typeof import('tdesign-vue-next')['Submenu']
  }
}
